I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 220, in script
    Ivanov "<{i}(увидев Боркина, вздрагивает и вскакивает).{/i}>"
Exception: Sayer 'Ivanov' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 220, in script
    Ivanov "<{i}(увидев Боркина, вздрагивает и вскакивает).{/i}>"
  File "/Users/happypuffin/Desktop/code/renpy-8.0.3-sdk/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/happypuffin/Desktop/code/renpy-8.0.3-sdk/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Ivanov' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
test 1.0
Sun Feb  5 21:27:23 2023
